// billingonaire-ui/src/routes/upload/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { auth } from '$lib/firebase';
  import { onAuthStateChanged } from 'firebase/auth';

  let file;
  let dataframe = null;
  let error = '';
  let isUploading = false;
  let tableData = [];
  let editedData = [];
  let skipPreview = false;
  let successMessage = '';

  const uploadFile = async () => {
    isUploading = true;
    console.log('File upload attempt:', file.name);
    const formData = new FormData();
    formData.append('file', file.files[0]);
    formData.append('skip_preview', skipPreview);

    try {
      const response = await fetch('http://localhost:8000/upload-pdf', {
        method: 'POST',
        body: formData,
        credentials: 'include'
      });

      if (!response.ok) {
        throw new Error('Failed to upload file');
      }

      const data = await response.json();
      if (skipPreview) {
        successMessage = data.message;
      } else {
        dataframe = data;
        tableData = data.data;
        editedData = JSON.parse(JSON.stringify(tableData));
      }
      console.log('File upload successful:', file.name);
    } catch (e) {
      console.error('File upload failed:', file.name, 'error:', e.message);
      error = e.message;
    } finally {
      isUploading = false;
    }
  };

  const saveData = async () => {
    try {
      const response = await fetch('http://localhost:8000/save-data', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(editedData),
        credentials: 'include'
      });

      if (!response.ok) {
        throw new Error('Failed to save data');
      }

      const result = await response.json();
      console.log('Data saved successfully:', result);
    } catch (e) {
      console.error('Failed to save data:', e.message);
      error = e.message;
    }
  };

  const cancelEdit = () => {
    editedData = JSON.parse(JSON.stringify(tableData));
  };

  const addRow = () => {
    editedData.push({});
  };

  const deleteRow = (index) => {
    editedData.splice(index, 1);
  };

  onMount(() => {
    onAuthStateChanged(auth, (user) => {
      if (!user) {
        goto('/login');
      }
    });
  });
</script>

<svelte:head>
  <title>Upload PDF</title>
</svelte:head>

<div class="upload-container">
  <h1>Upload PDF</h1>
  <form on:submit|preventDefault={uploadFile}>
    <div>
      <label for="file">Choose PDF file</label>
      <input type="file" id="file" accept="application/pdf" bind:this={file} required />
    </div>
    <div>
      <label for="skipPreview">Skip Preview</label>
      <input type="checkbox" id="skipPreview" bind:checked={skipPreview} />
    </div>
    {#if error}
      <p class="error">{error}</p>
    {/if}
    <button type="submit" disabled={isUploading}>Upload</button>
  </form>

  {#if successMessage}
    <p class="success">{successMessage}</p>
  {/if}

  {#if dataframe}
    <div class="dataframe">
      <h2>Dataframe</h2>
      <table>
        <thead>
          <tr>
            {#each Object.keys(editedData[0] || {}) as key}
              <th>{key}</th>
            {/each}
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {#each editedData as row, index}
            <tr>
              {#each Object.keys(row) as key}
                <td>
                  <input type="text" bind:value={row[key]} />
                </td>
              {/each}
              <td>
                <button on:click={() => deleteRow(index)}>Delete</button>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
      <button on:click={addRow}>Add Row</button>
      <button on:click={saveData}>Save</button>
      <button on:click={cancelEdit}>Cancel</button>
    </div>
  {/if}
</div>

<style>
  .upload-container {
    max-width: 600px;
    margin: 0 auto;
    padding: 1rem;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    background-color: #fff;
  }

  h1 {
    text-align: center;
    color: #333;
  }

  form {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  label {
    margin-bottom: 0.5rem;
    color: #333;
  }

  input {
    margin-bottom: 1rem;
    padding: 0.5rem;
    border: 1px solid #ccc;
    border-radius: 4px;
    width: 100%;
  }

  .error {
    color: red;
    margin-bottom: 1rem;
  }

  .success {
    color: green;
    margin-bottom: 1rem;
  }

  button {
    padding: 0.5rem;
    border: none;
    border-radius: 4px;
    background-color: #007bff;
    color: white;
    cursor: pointer;
    width: 100%;
  }

  button:hover {
    background-color: #0056b3;
  }

  .dataframe {
    margin-top: 1rem;
    width: 100%;
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    padding: 0.5rem;
    border: 1px solid #ccc;
    text-align: left;
  }

  th {
    background-color: #f8f8f8;
  }

  pre {
    background-color: #f8f8f8;
    padding: 1rem;
    border-radius: 4px;
    overflow-x: auto;
    width: 100%;
  }
</style>

// billingonaire-ui/src-react/src/Upload.jsx
import React, { useRef, useState } from 'react';
// import { useNavigate } from 'react-router-dom'; // Uncomment if using React Router
// import { auth } from '../lib/firebase'; // Adjust import if you migrate firebase logic
// import { onAuthStateChanged } from 'firebase/auth'; // Uncomment if using Firebase Auth
import { API_BASE_URL } from './config';

const Upload = () => {
  // const navigate = useNavigate(); // Uncomment if using React Router
  const fileInput = useRef();
  const [error, setError] = useState('');
  const [isUploading, setIsUploading] = useState(false);
  const [progress, setProgress] = useState({}); // Track progress per file
  const [fileResults, setFileResults] = useState({}); // Store backend response per file
  const [successMessage, setSuccessMessage] = useState('');

  // useEffect(() => {
  //   onAuthStateChanged(auth, (user) => {
  //     if (!user) {
  //       navigate('/login');
  //     }
  //   });
  // }, [navigate]);

  const uploadFile = async (e) => {
    e.preventDefault();
    setIsUploading(true);
    setError('');
    setProgress({});
    setFileResults({});
    const files = fileInput.current.files;
    if (!files.length) {
      setError('Please select at least one file.');
      setIsUploading(false);
      return;
    }
    // Upload all files in parallel
    await Promise.all(
      Array.from(files).map(async (file) => {
        const formData = new FormData();
        formData.append('files', file); // 'files' matches FastAPI param
        try {
          const xhr = new XMLHttpRequest();
          xhr.open('POST', `${API_BASE_URL}/upload-pdf`, true);
          xhr.withCredentials = true;
          xhr.upload.onprogress = (event) => {
            if (event.lengthComputable) {
              setProgress((prev) => ({ ...prev, [file.name]: Math.round((event.loaded / event.total) * 100) }));
            }
          };
          const uploadPromise = new Promise((resolve, reject) => {
            xhr.onload = () => {
              if (xhr.status >= 200 && xhr.status < 300) {
                resolve(JSON.parse(xhr.responseText));
              } else {
                reject(new Error(xhr.statusText));
              }
            };
            xhr.onerror = () => reject(new Error('Upload failed'));
          });
          xhr.send(formData);
          const result = await uploadPromise;
          // result.results is always an array, but we only sent one file
          const fileResult = result.results?.[0] || {};
          setFileResults((prev) => ({ ...prev, [file.name]: fileResult }));
        } catch (e) {
          setError(`Error uploading ${file.name}: ${e.message}`);
          setFileResults((prev) => ({ ...prev, [file.name]: { error: e.message } }));
        }
      })
    );
    setIsUploading(false);
    setSuccessMessage('Upload complete!');
  };

  return (
    <div className="upload-container">
      <h1>Upload PDF</h1>
      <form onSubmit={uploadFile}>
        <div>
          <label htmlFor="file">Choose PDF file(s)</label>
          <input type="file" id="file" accept="application/pdf" ref={fileInput} multiple required />
        </div>
        {error && <p className="error">{error}</p>}
        <button type="submit" disabled={isUploading}>
          Upload
        </button>
      </form>
      {successMessage && <p className="success">{successMessage}</p>}
      {Object.keys(progress).length > 0 && (
        <div>
          <h4>Upload Progress</h4>
          {Object.entries(progress).map(([name, percent]) => (
            <div key={name} style={{ marginBottom: '0.5rem' }}>
              <span>{name}: {percent}%</span>
              <progress value={percent} max="100" style={{ width: '100%' }} />
              {fileResults[name] && (
                <div style={{ marginTop: '0.25rem', color: fileResults[name].error ? 'red' : 'green' }}>
                  {fileResults[name].error
                    ? `Error: ${fileResults[name].error}`
                    : fileResults[name].message
                      ? fileResults[name].message
                      : 'Processed successfully'}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
      <style>{`
        .upload-container {
          max-width: 600px;
          margin: 0 auto;
          padding: 1rem;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
          background-color: #fff;
        }
        h1 {
          text-align: center;
          color: #333;
        }
        form {
          display: flex;
          flex-direction: column;
          align-items: center;
        }
        label {
          margin-bottom: 0.5rem;
          color: #333;
        }
        input {
          margin-bottom: 1rem;
          padding: 0.5rem;
          border: 1px solid #ccc;
          border-radius: 4px;
          width: 100%;
        }
        .error {
          color: red;
          margin-bottom: 1rem;
        }
        .success {
          color: green;
          margin-bottom: 1rem;
        }
        button {
          padding: 0.5rem;
          border: none;
          border-radius: 4px;
          background-color: #007bff;
          color: white;
          cursor: pointer;
          width: 100%;
        }
        button:hover {
          background-color: #0056b3;
        }
        h4 {
          margin-top: 1.5rem;
        }
      `}</style>
    </div>
  );
};

export default Upload;
