// billingonaire-ui/src/routes/table/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { auth } from '$lib/firebase';
  import { onAuthStateChanged } from 'firebase/auth';

  let data = [];
  let searchCriteria = {
    startDate: '',
    endDate: '',
    advocateName: '',
    caseNumber: '',
    caseType: '',
    caseYear: '',
    caseStage: ''
  };

  let editedData = [];

  const fetchData = async () => {
    if (!searchCriteria.startDate && !searchCriteria.endDate && !searchCriteria.advocateName && !searchCriteria.caseNumber && !searchCriteria.caseType && !searchCriteria.caseYear && !searchCriteria.caseStage) {
      alert('Please fill at least one search criteria');
      return;
    }

    try {
      const response = await fetch('http://localhost:8000/get-data', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(searchCriteria)
      });
      if (!response.ok) {
        throw new Error('Failed to fetch data');
      }
      data = await response.json();
      editedData = JSON.parse(JSON.stringify(data));
    } catch (e) {
      console.error(e);
    }
  };

  const filterData = () => {
    return data.filter(item => {
      const itemDate = new Date(item.Date);
      const startDate = new Date(searchCriteria.startDate);
      const endDate = new Date(searchCriteria.endDate);
      const advocateName = searchCriteria.advocateName.toLowerCase();
      const caseNumber = searchCriteria.caseNumber.toLowerCase();
      const caseType = searchCriteria.caseType.toLowerCase();
      const caseYear = searchCriteria.caseYear.toLowerCase();
      const caseStage = searchCriteria.caseStage.toLowerCase();

      return (
        (!searchCriteria.startDate || itemDate >= startDate) &&
        (!searchCriteria.endDate || itemDate <= endDate) &&
        (!searchCriteria.advocateName || item['Advocate Name'].toLowerCase().includes(advocateName)) &&
        (!searchCriteria.caseNumber || item['Case Number'].toLowerCase().includes(caseNumber)) &&
        (!searchCriteria.caseType || item['Case Type'].toLowerCase().includes(caseType)) &&
        (!searchCriteria.caseYear || item['Case Year'].toLowerCase().includes(caseYear)) &&
        (!searchCriteria.caseStage || item['Case Stage'].toLowerCase().includes(caseStage))
      );
    });
  };

  const saveData = async () => {
    try {
      const response = await fetch('http://localhost:8000/save-data', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(editedData),
        credentials: 'include'
      });

      if (!response.ok) {
        throw new Error('Failed to save data');
      }

      const result = await response.json();
      console.log('Data saved successfully:', result);
    } catch (e) {
      console.error('Failed to save data:', e.message);
    }
  };

  const cancelEdit = () => {
    editedData = JSON.parse(JSON.stringify(data));
  };

  const addRow = () => {
    editedData.push({});
  };

  const deleteRow = (index) => {
    editedData.splice(index, 1);
  };

  onMount(() => {
    onAuthStateChanged(auth, (user) => {
      if (!user) {
        goto('/login');
      } else {
        const today = new Date().toISOString().split('T')[0];
        searchCriteria.startDate = today;
        fetchData();
      }
    });
  });

  const columns = [
    { key: 'Date', label: 'Date', editable: true },
    { key: 'Case Type', label: 'Case Type', editable: true },
    { key: 'Case Number', label: 'Case Number', editable: true },
    { key: 'Case Year', label: 'Case Year', editable: true },
    { key: 'Case Stage', label: 'Case Stage', editable: true },
    { key: 'Advocate Name', label: 'Advocate Name', editable: true },
    { key: 'Actions', label: 'Actions', editable: false }
  ];
</script>

<svelte:head>
  <title>Table Data</title>
</svelte:head>

<div class="table-container">
  <h1>Table Data</h1>

  <div class="search-criteria">
    <label for="startDate">Start Date</label>
    <input type="date" id="startDate" bind:value={searchCriteria.startDate} class="mb-2 p-2 border border-gray-300 rounded" />

    <label for="endDate">End Date</label>
    <input type="date" id="endDate" bind:value={searchCriteria.endDate} class="mb-2 p-2 border border-gray-300 rounded" />

    <label for="advocateName">Advocate Name</label>
    <input type="text" id="advocateName" bind:value={searchCriteria.advocateName} class="mb-2 p-2 border border-gray-300 rounded" />

    <label for="caseNumber">Case Number</label>
    <input type="text" id="caseNumber" bind:value={searchCriteria.caseNumber} class="mb-2 p-2 border border-gray-300 rounded" />

    <label for="caseType">Case Type</label>
    <select id="caseType" bind:value={searchCriteria.caseType} class="mb-2 p-2 border border-gray-300 rounded">
      <option value="">Select Case Type</option>
      <option value="WP">WP</option>
      <option value="IA">IA</option>
      <option value="CP">CP</option>
      <option value="PIL">PIL</option>
      <option value="CAW">CAW</option>
    </select>

    <label for="caseYear">Case Year</label>
    <input type="text" id="caseYear" bind:value={searchCriteria.caseYear} class="mb-2 p-2 border border-gray-300 rounded" />

    <label for="caseStage">Case Stage</label>
    <select id="caseStage" bind:value={searchCriteria.caseStage} class="mb-2 p-2 border border-gray-300 rounded">
      <option value="">Select Case Stage</option>
      <option value="Registration">Registration</option>
      <option value="Stamp">Stamp</option>
    </select>

    <button on:click={fetchData} class="mb-2 p-2 bg-blue-500 text-white rounded">Search</button>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full bg-white border border-gray-300">
      <thead>
        <tr>
          {#each columns as column}
            <th class="py-2 px-4 border-b border-gray-300">{column.label}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each editedData as row, index}
          <tr>
            {#each columns as column}
              <td class="py-2 px-4 border-b border-gray-300">
                {#if column.key === 'Actions'}
                  <button on:click={() => deleteRow(index)} class="mr-2 p-1 bg-red-500 text-white rounded">Delete</button>
                {:else}
                  <input type="text" bind:value={row[column.key]} class="w-full p-1 border border-gray-300 rounded" />
                {/if}
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <button on:click={addRow} class="mt-2 p-2 bg-green-500 text-white rounded">Add Row</button>
  <button on:click={saveData} class="mt-2 p-2 bg-blue-500 text-white rounded">Save</button>
  <button on:click={cancelEdit} class="mt-2 p-2 bg-gray-500 text-white rounded">Cancel</button>
</div>

<style>
  .table-container {
    max-width: 800px;
    margin: 0 auto;
    padding: 1rem;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  h1 {
    text-align: center;
  }

  .search-criteria {
    display: flex;
    flex-direction: column;
    margin-bottom: 1rem;
  }

  .search-criteria label {
    margin-bottom: 0.5rem;
  }

  .search-criteria input,
  .search-criteria select {
    margin-bottom: 1rem;
    padding: 0.5rem;
    border: 1px solid #ccc;
    border-radius: 4px;
  }

  .search-criteria button {
    padding: 0.5rem;
    border: none;
    border-radius: 4px;
    background-color: #007bff;
    color: white;
    cursor: pointer;
  }

  .search-criteria button:hover {
    background-color: #0056b3;
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    padding: 0.5rem;
    border: 1px solid #ccc;
    text-align: left;
  }

  th {
    background-color: #f8f8f8;
  }
</style>

// billingonaire-ui/src/Table.jsx
import React, { useEffect, useState } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ModuleRegistry, AllCommunityModule } from 'ag-grid-community';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import { authenticatedFetchJSON } from './lib/api';
import './styles/professional.css';

// Register AG Grid modules
ModuleRegistry.registerModules([AllCommunityModule]);

const Table = () => {
  const [data, setData] = useState([]);
  const [editedData, setEditedData] = useState([]);
  const [searchCriteria, setSearchCriteria] = useState({
    startDate: '',
    endDate: '',
    advocateName: '',
    caseNumber: '',
    caseType: '',
    caseYear: '',
    caseStage: ''
  });
  const [appliedCriteria, setAppliedCriteria] = useState({
    startDate: '',
    endDate: '',
    advocateName: '',
    caseNumber: '',
    caseType: '',
    caseYear: '',
    caseStage: ''
  });
  const [searchOpen, setSearchOpen] = useState(false);
  const [isSearching, setIsSearching] = useState(false);
  const [searchError, setSearchError] = useState('');

  useEffect(() => {
    // By default, show last 3 months data
    const today = new Date();
    const threeMonthsAgo = new Date();
    threeMonthsAgo.setMonth(today.getMonth() - 3);
    
    const endDate = today.toISOString().split('T')[0];
    const startDate = threeMonthsAgo.toISOString().split('T')[0];
    
    const initialCriteria = { 
      startDate, 
      endDate, 
      advocateName: '', 
      caseNumber: '', 
      caseType: '', 
      caseYear: '', 
      caseStage: '' 
    };
    
    setSearchCriteria(initialCriteria);
    setAppliedCriteria(initialCriteria);
    fetchData(initialCriteria);
    // eslint-disable-next-line
  }, []);

  const fetchData = async (criteria = searchCriteria) => {
    if (!criteria.startDate && !criteria.endDate && !criteria.advocateName && !criteria.caseNumber && !criteria.caseType && !criteria.caseYear && !criteria.caseStage) {
      setSearchError('Please fill at least one search criteria');
      return;
    }

    setIsSearching(true);
    setSearchError('');
    
    // Store the criteria that are actually being applied
    setAppliedCriteria({ ...criteria });
    
    try {
      const result = await authenticatedFetchJSON('/get-data', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          startDate: criteria.startDate,
          endDate: criteria.endDate,
          advocateName: criteria.advocateName,
          caseNumber: criteria.caseNumber,
          caseType: criteria.caseType,
          caseYear: criteria.caseYear,
          caseStage: criteria.caseStage
        })
      });
      console.log('🔍 API Response received:', result);
      console.log('📊 Data type:', typeof result, 'Length:', Array.isArray(result) ? result.length : 'Not array');
      console.log('📋 First 3 records:', Array.isArray(result) ? result.slice(0, 3) : result);
      console.log('🎯 Applied search criteria:', criteria);
      setData(result);
      setEditedData(JSON.parse(JSON.stringify(result)));
      console.log('✅ Data set to state. Current data length:', Array.isArray(result) ? result.length : 'Not array');
    } catch (e) {
      console.error('Search failed:', e);
      setSearchError('Search failed. Please check your criteria and try again.');
    } finally {
      setIsSearching(false);
    }
  };

  const saveData = async () => {
    try {
      await authenticatedFetchJSON('/save-data', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(editedData)
      });
      alert('Data saved successfully!');
    } catch (e) {
      console.error('Failed to save data:', e.message);
      alert('Failed to save data. Please try again.');
    }
  };

  const cancelEdit = () => {
    setEditedData(JSON.parse(JSON.stringify(data)));
  };

  const addRow = () => {
    setEditedData((prev) => [...prev, {}]);
  };

  const deleteRow = (index) => {
    setEditedData((prev) => prev.filter((_, i) => i !== index));
  };

  // AG Grid column definitions
  const columnDefs = [
    { 
      headerName: 'Board Date', 
      field: 'board_date', 
      sortable: true, 
      filter: 'agDateColumnFilter',
      editable: true,
      width: 150
    },
    { 
      headerName: 'Case Type', 
      field: 'case_type', 
      sortable: true, 
      filter: 'agTextColumnFilter',
      editable: true,
      width: 120
    },
    { 
      headerName: 'Case Number', 
      field: 'case_no', 
      sortable: true, 
      filter: 'agTextColumnFilter',
      editable: true,
      width: 150
    },
    { 
      headerName: 'Case Year', 
      field: 'case_year', 
      sortable: true, 
      filter: 'agNumberColumnFilter',
      editable: true,
      width: 120
    },
    { 
      headerName: 'Petitioner', 
      field: 'petitioner_name', 
      sortable: true, 
      filter: 'agTextColumnFilter',
      editable: true,
      width: 200
    },
    { 
      headerName: 'Respondent', 
      field: 'respondent_name', 
      sortable: true, 
      filter: 'agTextColumnFilter',
      editable: true,
      width: 200
    },
    { 
      headerName: 'AGP Name', 
      field: 'respondent_lawyer', 
      sortable: true, 
      filter: 'agTextColumnFilter',
      editable: true,
      width: 180
    },
    { 
      headerName: 'Court Order', 
      field: 'court_order', 
      sortable: true, 
      filter: 'agSetColumnFilter',
      editable: true,
      width: 150,
      cellStyle: params => {
        if (params.value === 'DISPOSAL') return { backgroundColor: '#d4edda', color: '#155724' };
        if (params.value === 'ADJOURNMENT') return { backgroundColor: '#fff3cd', color: '#856404' };
        if (params.value === 'HEARD & ADJRN') return { backgroundColor: '#cce7ff', color: '#004085' };
        return null;
      }
    },
    { 
      headerName: 'Actions', 
      field: 'actions',
      cellRenderer: 'deleteButtonRenderer',
      width: 100,
      pinned: 'right'
    }
  ];

  // Custom cell renderer for delete button
  const DeleteButtonRenderer = (props) => {
    const handleDelete = () => {
      const rowIndex = props.rowIndex;
      setEditedData(prev => prev.filter((_, i) => i !== rowIndex));
    };

    return (
      <button 
        className="btn-professional btn-danger" 
        style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}
        onClick={handleDelete}
      >
        Delete
      </button>
    );
  };

  const components = {
    deleteButtonRenderer: DeleteButtonRenderer
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1 className="dashboard-title">🔍 Advanced Search & Data Management</h1>
        <p className="dashboard-subtitle">
          Search court cases and AGP assignments with powerful filters and professional data grid
        </p>
      </div>

      <div className="dashboard-section">
        {/* Elegant Search Criteria Card */}
        <div className="card-professional" style={{ marginBottom: 'var(--spacing-xl)' }}>
          <div className="card-header">
            <h2 className="section-title">📋 Search Criteria</h2>
            <button 
              className="btn-professional btn-secondary"
              onClick={() => setSearchOpen(!searchOpen)}
              style={{ fontSize: '0.875rem' }}
            >
              {searchOpen ? 'Hide Filters' : 'Show Filters'}
            </button>
          </div>
          {searchOpen && (
            <div className="card-body">
              <div style={{ 
                display: 'grid', 
                gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', 
                gap: 'var(--spacing-lg)',
                marginBottom: 'var(--spacing-lg)'
              }}>
                <div className="form-group">
                  <label className="form-label">Start Date</label>
                  <input
                    type="date"
                    className="form-control"
                    value={searchCriteria.startDate}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, startDate: e.target.value }))}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">End Date</label>
                  <input
                    type="date"
                    className="form-control"
                    value={searchCriteria.endDate}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, endDate: e.target.value }))}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">AGP/Advocate Name</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter advocate name..."
                    value={searchCriteria.advocateName}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, advocateName: e.target.value }))}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Case Number</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter case number..."
                    value={searchCriteria.caseNumber}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, caseNumber: e.target.value }))}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Case Type</label>
                  <select
                    className="form-control"
                    value={searchCriteria.caseType}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, caseType: e.target.value }))}
                  >
                    <option value="">All Case Types</option>
                    <option value="WP">WP - Writ Petition</option>
                    <option value="IA">IA - Interim Application</option>
                    <option value="CP">CP - Civil Petition</option>
                    <option value="PIL">PIL - Public Interest Litigation</option>
                    <option value="CAW">CAW - Civil Appeal Writ</option>
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Case Year</label>
                  <input
                    type="number"
                    className="form-control"
                    placeholder="e.g., 2025"
                    value={searchCriteria.caseYear}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, caseYear: e.target.value }))}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Case Stage</label>
                  <select
                    className="form-control"
                    value={searchCriteria.caseStage}
                    onChange={e => setSearchCriteria(sc => ({ ...sc, caseStage: e.target.value }))}
                  >
                    <option value="">All Stages</option>
                    <option value="Registration">Registration</option>
                    <option value="Stamp">Stamp</option>
                  </select>
                </div>
                <div style={{ display: 'flex', alignItems: 'end', gap: 'var(--spacing-md)' }}>
                  <button 
                    className="btn-professional btn-primary"
                    onClick={() => fetchData()}
                    disabled={isSearching}
                    style={{ 
                      flex: 1,
                      opacity: isSearching ? 0.7 : 1,
                      cursor: isSearching ? 'not-allowed' : 'pointer'
                    }}
                  >
                    {isSearching ? (
                      <>
                        <span className="loading" style={{ marginRight: '8px' }}></span>
                        Searching...
                      </>
                    ) : (
                      '🔍 Search Cases'
                    )}
                  </button>
                  <button 
                    className="btn-professional btn-secondary"
                    disabled={isSearching}
                    onClick={() => {
                      setSearchCriteria({
                        startDate: '',
                        endDate: '',
                        advocateName: '',
                        caseNumber: '',
                        caseType: '',
                        caseYear: '',
                        caseStage: ''
                      });
                      setSearchError('');
                    }}
                    style={{
                      opacity: isSearching ? 0.7 : 1,
                      cursor: isSearching ? 'not-allowed' : 'pointer'
                    }}
                  >
                    Clear
                  </button>
                </div>
                
                {/* Progress Bar */}
                {isSearching && (
                  <div style={{ marginTop: 'var(--spacing-md)' }}>
                    <div style={{
                      width: '100%',
                      height: '4px',
                      backgroundColor: 'var(--gray-200)',
                      borderRadius: '2px',
                      overflow: 'hidden'
                    }}>
                      <div style={{
                        width: '100%',
                        height: '100%',
                        background: 'linear-gradient(90deg, var(--primary-color) 0%, var(--primary-light) 100%)',
                        animation: 'progress-slide 2s ease-in-out infinite'
                      }}></div>
                    </div>
                    <p style={{ 
                      marginTop: '8px', 
                      fontSize: '0.875rem', 
                      color: 'var(--gray-600)', 
                      textAlign: 'center' 
                    }}>
                      Searching through case database... Please wait
                    </p>
                  </div>
                )}
                
                {/* Error Message */}
                {searchError && (
                  <div style={{
                    marginTop: 'var(--spacing-md)',
                    padding: 'var(--spacing-sm)',
                    backgroundColor: 'var(--error-bg)',
                    border: '1px solid var(--error-border)',
                    borderRadius: 'var(--radius-md)',
                    color: 'var(--error-color)'
                  }}>
                    {searchError}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Applied Search Criteria Display */}
        {(appliedCriteria.startDate || appliedCriteria.endDate || appliedCriteria.advocateName || appliedCriteria.caseNumber || appliedCriteria.caseType || appliedCriteria.caseYear || appliedCriteria.caseStage) && (
          <div className="card-professional" style={{ marginBottom: 'var(--spacing-lg)', backgroundColor: 'var(--success-bg)' }}>
            <div className="card-header">
              <h3 className="section-title" style={{ color: 'var(--success-color)', fontSize: '1rem' }}>
                🎯 Applied Search Filters
              </h3>
            </div>
            <div className="card-body" style={{ padding: 'var(--spacing-md)' }}>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--spacing-sm)' }}>
                {appliedCriteria.startDate && (
                  <span className="badge bg-primary">
                    Start Date: {appliedCriteria.startDate}
                  </span>
                )}
                {appliedCriteria.endDate && (
                  <span className="badge bg-primary">
                    End Date: {appliedCriteria.endDate}
                  </span>
                )}
                {appliedCriteria.advocateName && (
                  <span className="badge bg-primary">
                    Advocate: {appliedCriteria.advocateName}
                  </span>
                )}
                {appliedCriteria.caseNumber && (
                  <span className="badge bg-primary">
                    Case Number: {appliedCriteria.caseNumber}
                  </span>
                )}
                {appliedCriteria.caseType && (
                  <span className="badge bg-primary">
                    Case Type: {appliedCriteria.caseType}
                  </span>
                )}
                {appliedCriteria.caseYear && (
                  <span className="badge bg-primary">
                    Case Year: {appliedCriteria.caseYear}
                  </span>
                )}
                {appliedCriteria.caseStage && (
                  <span className="badge bg-primary">
                    Case Stage: {appliedCriteria.caseStage}
                  </span>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Professional AG Grid */}
        <div className="card-professional">
          <div className="card-header">
            <h2 className="section-title">📊 Case Data ({data.length} records)</h2>
            <div style={{ display: 'flex', gap: 'var(--spacing-md)' }}>
              <button 
                className="btn-professional btn-success"
                onClick={addRow}
                style={{ fontSize: '0.875rem' }}
              >
                + Add Row
              </button>
              <button 
                className="btn-professional btn-primary"
                onClick={saveData}
                style={{ fontSize: '0.875rem' }}
              >
                💾 Save Changes
              </button>
              <button 
                className="btn-professional btn-secondary"
                onClick={cancelEdit}
                style={{ fontSize: '0.875rem' }}
              >
                ↶ Cancel
              </button>
            </div>
          </div>
          <div className="card-body" style={{ padding: 0 }}>
            <div 
              className="ag-theme-alpine"
              style={{ 
                height: '600px', 
                width: '100%',
                '--ag-font-family': 'var(--font-main)',
                '--ag-font-size': '14px',
                '--ag-header-background-color': 'var(--gray-50)',
                '--ag-header-foreground-color': 'var(--gray-900)',
                '--ag-odd-row-background-color': 'var(--gray-25)',
                '--ag-border-color': 'var(--gray-200)'
              }}
            >
              <AgGridReact
                rowData={editedData}
                columnDefs={columnDefs}
                components={components}
                defaultColDef={{
                  flex: 1,
                  minWidth: 100,
                  resizable: true,
                  sortable: true,
                  filter: true,
                  editable: true
                }}
                gridOptions={{
                  animateRows: true,
                  pagination: true,
                  paginationPageSize: 50,
                  domLayout: 'normal',
                  rowSelection: { mode: 'multiRow' }
                }}
                onCellValueChanged={(params) => {
                  const rowIndex = params.rowIndex;
                  const field = params.colDef.field;
                  const newValue = params.newValue;
                  setEditedData(prev => prev.map((row, index) => 
                    index === rowIndex ? { ...row, [field]: newValue } : row
                  ));
                }}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Table;
